services:
  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_USER: course_user
      POSTGRES_PASSWORD: course_user_password
      POSTGRES_DB: coursehub
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  course-hub-frontend:
    image: ghcr.io/hackyourfuture/course-hub-frontend:latest
    container_name: course-hub-frontend
    environment:
      BACKEND_URL: http://localhost:8080
    ports:
      - "3000:3000"

