services:
  postgres:
    image: postgres:17
    container_name: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: course_user
      POSTGRES_PASSWORD: course_user_password
      POSTGRES_DB: coursehub
    ports:
      - "5432:5432"
