name: Build
on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths:
      - 'backend/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

concurrency:
  # On main, we don't want any jobs cancelled, so the SHA hash is used to name the group
  # On PR branches, we cancel the job if new commits are pushed
  # More info: https://stackoverflow.com/a/68422069/253468
  group: ${{ (github.ref == 'refs/heads/main') && format('{0}-{1}', github.workflow_ref, github.sha) || format('{0}-{1}', github.workflow_ref, github.head_ref) }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      checks: write # for publishing test results and annotations
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up docker compose environment
        run: docker compose up -d

      - name: Build
        run: ./gradlew build

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: ${{ !cancelled() }} # always run even if the previous step fails
        with:
          report_paths: '**/backend/build/test-results/test/TEST-*.xml'
